# Generated by Django 5.0.7 on 2024-07-25 13:13

from django.db import migrations

def update_urls(apps, schema_editor):
    Post = apps.get_model('news', 'Post')
    for post in Post.objects.all():
        if post.image and post.image.url.startswith('http://'):
            new_url = post.image.url.replace('http://', 'https://')
            post.image = new_url
            post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_update_cloudinary_urls'),  # Update with your actual latest migration
    ]

    operations = [
        migrations.RunPython(update_urls),
    ]
