# Generated by Django 5.0.7 on 2024-07-26 17:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_post_image_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/deal48hya/image/upload/v1722015477/puzzle-654963_1280_aotr8m.jpg', max_length=255, verbose_name='image'),
        ),
    ]
